### ISSUE TITLE
9.2.1 Compare 10.2.2 Error

### ISSUE THREAD

**Issue by zcinclude** [stijnster/NSString-compareToVersion#5]
<img width="1280" alt="2018-01-22 16 48 45" src="https://user-images.githubusercontent.com/12709000/35212169-4874189e-ff94-11e7-9cc9-b3ad03320616.png">

**Comment by stijnster** [comment]
Hi zcinclude,

thanks for your feedback. I see that you have altered the expected results in the test and that the test now returns unexpected results.

This is however expected behaviour.

The idea behind this, is that you are able to determine to upgrade to a certain point (or sub-version) release within the same main version. Changing the main versions (from 9 to 10) will therefor not give a positive result.

Please help me to understand what behaviour you would expect from this.

If you simple want to check wether the new version is higher then your current version (say 9.2.1 vs. 10.2.2) you should use; isEqualOrNewerThanVersion.

Kind regards,

Stijn

**Comment by zcinclude** [comment]
好的 非常感谢 stijnster，

我想是我对方法名的理解存在误解。

你做的版本比较工具非常好。

再次感谢，

zcinclude

**Comment by stijnster** [comment]
You're welcome!
